### ISSUE TITLE
The atom-live-server always open the highest positioned project

### ISSUE THREAD

**Issue by toolbox1972** [jas-chen/atom-live-server#167] opened 2018-05-03 06:38 UTC
If having several projects added in atom, when clicking any of the open atom project the atom-live-server will always open the highest positioned project. This can be confusing for the user since despite of the settings you add in atom-live-server, the order of the projects rules. Not saying this is a a bug, maybe good to add in the instructions.

**Comment by Kagerjay** [comment] 2018-05-30 20:45
I have this same problem as well, I like having multiple projects open in one pane too

**Comment by richiksc** [comment] 2018-06-07 00:12
Duplicate of #128.

**Closed** 2018-06-07 01:50 UTC
